version: 2
jobs:
  build:
    docker:
      - image: paperist/alpine-texlive-ja
    working_directory: ~/slide
    steps:
      - checkout
      - run:
          name: Make dvi
          command: |
            for filepath in `ls **/*.tex`
            do
              cd `dirname $filepath` && \
              platex `basename $filepath` && \
              platex `basename $filepath`
            done

  lint:
    docker:
      - image: circleci/node:8
    working_directory: ~/slide
    steps:
      - checkout
      - run:
          name: Install packages
          command: |
            curl -fSL https://github.com/haya14busa/reviewdog/releases/download/0.9.9/reviewdog_linux_amd64 -o ./reviewdog
            chmod +x ./reviewdog
      - restore_cache:
          keys:
            - yarn-cache-{{ checksum "yarn.lock" }}
            - yarn-cache-
      - run:
          name: Install libraries
          command: yarn install
      - save_cache:
          key: yarn-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Lint
          command: |
            test $CI_PULL_REQUEST && \
            for filepath in `git diff origin/master --name-only`
            do
              [[ ! $filepath =~ \.tex$ ]] && continue
              echo $filepath
              yarn textlint -f checkstyle $filepath | ./reviewdog -f=checkstyle -name=textlint -ci="circle-ci" -reporter=github-pr-check
            done || echo "No lint"

workflows:
  version: 2
  do:
    jobs:
      - build
      - lint:
          requires:
            - build
